# Generated by Django 4.1.4 on 2023-04-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_blog_id_blog_bno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('ano', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=100)),
                ('starttime', models.DateTimeField(unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
    ]
