# Generated by Django 4.1.4 on 2023-04-29 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime.now, unique=True),
        ),
    ]
