# Generated by Django 4.1.4 on 2023-04-29 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_appointment_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 15, 30, 11, 245410)),
        ),
    ]
