# Generated by Django 4.1.4 on 2023-04-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_appointment_starttime_appointment_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dt',
        ),
        migrations.AddField(
            model_name='appointment',
            name='starttime',
            field=models.DateTimeField(default='2023-04-29'),
        ),
    ]
