# Generated by Django 4.1.4 on 2023-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_appointment_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='starttime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dt',
            field=models.DateField(default='2023-04-29'),
        ),
    ]
