# Generated by Django 4.1.4 on 2023-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_appointment_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dt',
        ),
        migrations.AddField(
            model_name='appointment',
            name='starttime',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
