# Generated by Django 4.1.4 on 2023-04-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_appointment_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='starttime',
        ),
    ]
