# Generated by Django 4.1.4 on 2023-04-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='speciality',
        ),
    ]
