# Generated by Django 4.1.4 on 2023-04-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_appointment_speciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
